name: Auto Tag on Push or PR Merge

on:
  push:
    branches:
      - main    # or any branch you want the action to trigger on
  pull_request:
    branches:
      - main    # trigger when PR is merged into the main branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Get current version
        id: get_version
        run: |
          # Try to get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "Latest tag: $latest_tag"
          
          # If no tag is found, default to v1.0.0
          if [ -z "$latest_tag" ]; then
            echo "No tags found. Starting with v1.0.0"
            echo "::set-output name=tag::v1.0.0"
          else
            # Increment the tag number
            version_number=$(echo $latest_tag | sed 's/v//')
            new_version_number=$((version_number + 1))
            new_tag="v$new_version_number"
            echo "::set-output name=tag::$new_tag"
          fi

      - name: Create and push new tag
        run: |
          new_tag=${{ steps.get_version.outputs.tag }}
          git tag $new_tag
          git push origin $new_tag
