name: Release Motivision Extension

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch: # Manual trigger

jobs:
  release:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Set version dynamically
      - name: Set Version to Today's Date
        id: set_version
        run: echo "VERSION=$(date +'%y.%m.%d')" >> $GITHUB_ENV
        shell: bash

      # Build Chrome and Firefox artifacts
      - name: Build Chrome and Firefox
        run: npm run build

      # Create Zip for Chrome
      - name: Zip Chrome Extension
        run: |
          mkdir -p artifacts
          powershell Compress-Archive -Path dist/chrome/* -DestinationPath artifacts/chrome-extension.zip

      # Create Zip for Firefox
      - name: Zip Firefox Extension
        run: |
          mkdir -p artifacts
          powershell Compress-Archive -Path dist/firefox/* -DestinationPath artifacts/firefox-extension.zip

      # Upload Zipped Chrome Artifact
      - name: Upload Chrome Extension as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: artifacts/chrome-extension.zip

      # Upload Zipped Firefox Artifact
      - name: Upload Firefox Extension as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: artifacts/firefox-extension.zip

      # Download artifacts to prepare for release
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      # Generate Release Notes
      - name: Generate Release Notes
        id: generate_notes
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          version: ${{ env.VERSION }}

      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            ${{ steps.generate_notes.outputs.body }}
          files: |
            artifacts/chrome-extension.zip
            artifacts/firefox-extension.zip
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
